// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_api.DataAccess.Concretes;

#nullable disable

namespace backend_api.Migrations.OyuncuKayitDb
{
    [DbContext(typeof(OyuncuKayitDbContext))]
    partial class OyuncuKayitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_api.DataAccess.Concretes.DahaOnceKatildigiLigTablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LigAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UlusalLiglerdeOynadiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("oyuncuTemelBilgilerTabloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("oyuncuTemelBilgilerTabloId")
                        .IsUnique();

                    b.ToTable("DahaOnceKatildigiLigTablo");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.MacEsTablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CiftEsAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CiftMacTercihi")
                        .HasColumnType("boolean");

                    b.Property<string>("KarisikEsAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KarisikMacTercihi")
                        .HasColumnType("boolean");

                    b.Property<int>("oyuncuTemelBilgilerTabloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("oyuncuTemelBilgilerTabloId")
                        .IsUnique();

                    b.ToTable("MacEsTablo");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.OyuncuTemelBilgilerTablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedenOlcusu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DahaOnceKatildiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("DogumYili")
                        .HasColumnType("integer");

                    b.Property<string>("EpostaAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OyunSeviye")
                        .HasColumnType("integer");

                    b.Property<int>("Oyuncu_Unic_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OyuncuTemelBilgiler");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.UcretTablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OdemeYapanKisininAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OdemeYapilmasiPlanlananTarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UcretOdemesiYapildiMi")
                        .HasColumnType("boolean");

                    b.Property<int>("oyuncuTemelBilgilerTabloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("oyuncuTemelBilgilerTabloId")
                        .IsUnique();

                    b.ToTable("UcretTablo");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.DahaOnceKatildigiLigTablo", b =>
                {
                    b.HasOne("backend_api.DataAccess.Concretes.OyuncuTemelBilgilerTablo", "oyuncuTemelBilgilerTablo")
                        .WithOne("DahaOnceKatildigiLigTablo")
                        .HasForeignKey("backend_api.DataAccess.Concretes.DahaOnceKatildigiLigTablo", "oyuncuTemelBilgilerTabloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oyuncuTemelBilgilerTablo");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.MacEsTablo", b =>
                {
                    b.HasOne("backend_api.DataAccess.Concretes.OyuncuTemelBilgilerTablo", "oyuncuTemelBilgilerTablo")
                        .WithOne("MacEsTablo")
                        .HasForeignKey("backend_api.DataAccess.Concretes.MacEsTablo", "oyuncuTemelBilgilerTabloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oyuncuTemelBilgilerTablo");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.UcretTablo", b =>
                {
                    b.HasOne("backend_api.DataAccess.Concretes.OyuncuTemelBilgilerTablo", "oyuncuTemelBilgilerTablo")
                        .WithOne("UcretTablo")
                        .HasForeignKey("backend_api.DataAccess.Concretes.UcretTablo", "oyuncuTemelBilgilerTabloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oyuncuTemelBilgilerTablo");
                });

            modelBuilder.Entity("backend_api.DataAccess.Concretes.OyuncuTemelBilgilerTablo", b =>
                {
                    b.Navigation("DahaOnceKatildigiLigTablo")
                        .IsRequired();

                    b.Navigation("MacEsTablo")
                        .IsRequired();

                    b.Navigation("UcretTablo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
